src/main/java/TodoList.java

Squashed the two changes into a new branch because a lot of files were erroneously removed in the old branch.
Contributors to this addition are Tahseen and Jenci.
The earlier created TodoList.java was an accidental merge from an incomplete branch into one of the other PR git histories.

Added TodoList (merged Jenci and Tahseen's classes)

---

crcCards/EventScheduler.txt
src/main/java/Calendar.java
src/main/java/EventScheduler.java
src/main/java/TaskToEvent.java
src/main/java/TaskToEventAuto.java
src/main/java/TaskToEventManual.java
src/main/java/TodoList.java

#8  
Created EventScheduler from CalendarBuilder and some methods from Calendar

EventScheduler Class

---

src/main/java/controller/EventController.java
src/main/java/controller/TaskController.java
src/main/java/entity/TodoList.java
src/main/java/use_case/AccessCalendarData.java
src/main/java/use_case/TaskAdder.java
src/main/java/use_case/TaskGetter.java

Deleted some unused imports. It's possible that some of them were unused because of commented out code, but they can be easily readded when needed.

cleaned up some unused imports

---

crcCards/controllers/TaskToEventAutoController
crcCards/controllers/TaskToEventController
crcCards/controllers/TaskToEventManualController
crcCards/use_case/TaskToEvent
crcCards/use_case/TaskToEventAuto
crcCards/use_case/TaskToEventManual
src/main/java/ApplicationDriver.java
src/main/java/controller/EventController.java
src/main/java/controller/MainController.java
src/main/java/controller/TaskController.java
src/main/java/controller/TaskEventAutoController.java
src/main/java/controller/TaskEventManualController.java
src/main/java/controller/TaskToEventAutoController.java
src/main/java/controller/TaskToEventConsoleController.java
src/main/java/controller/TaskToEventController.java
src/main/java/controller/TaskToEventManualController.java
src/main/java/entity/Task.java
src/main/java/use_case/EventScheduler.java
src/main/java/use_case/TaskGetter.java
src/main/java/use_case/TaskToEvent.java
src/main/java/use_case/TaskToEventAuto.java
src/main/java/use_case/TaskToEventManual.java

Implemented #5 on ApplicationDriver

Controllers

---

src/tests/TaskAdderTest.java
src/tests/TaskGetterTest.java

Whoop seems likes I accidentally didn't git add some of the test files I was trying to write in #36. They got outdated which prevents the current main from compiling.
Seems like a small change so first person to review can just merge it

update test references (follow up from #36)

---

src/main/java/interface_adapters/EventController.java
src/main/java/interface_adapters/MainController.java
src/main/java/interface_adapters/TaskToEventController.java

protected makes it difficult to repackage.
This is a preliminary PR to help repackage the project.

changed event controller modifiers to be private instead of protected

---

src/tests/CalendarTest.java
src/tests/EventTest.java
src/tests/TaskAdderTest.java
src/tests/TaskGetterTest.java
src/tests/TaskTest.java
src/tests/TodoListTest.java

Added ids to entity creation and updated import references

fixed import and breaking change errors

---

src/tests/TaskAdderTest.java
src/tests/TaskGetterTest.java

short PR just to get the application running again

added missing methods

---

src/main/java/console_app/ApplicationDriver.java
src/main/java/console_app/MainController.java
src/main/java/console_app/event_adapters/ConsoleEventPresenter.java
src/main/java/console_app/event_adapters/EventController.java
src/main/java/console_app/task_adapters/ConsoleTaskPresenter.java
src/main/java/console_app/task_adapters/TaskController.java
src/main/java/services/event_from_task_creation/TaskToEvent.java
src/main/java/services/event_presentation/CalendarEventDisplayBoundary.java
src/main/java/services/event_presentation/CalendarEventPresenter.java
src/main/java/services/event_presentation/EventGetter.java
src/main/java/services/event_presentation/GetEvent.java
src/main/java/services/task_presentation/TaskGetter.java
src/main/java/services/task_presentation/TodoListDisplayBoundary.java
src/main/java/services/task_presentation/TodoListPresenter.java
src/tests/CalendarTest.java
src/tests/TaskGetterTest.java
src/tests/TaskTest.java
src/tests/TodoListTest.java

The previous few pull requests messed up our console app so I have edited it and made it work again. 
Also, actions 5 and 6 are not exactly following the dependency rule (controllers should not be receiving the output value from the use cases but I think it would be too much work to decouple the console app code so I left it as such. we should think more thoroughly for our gui to ensure it doesn't happen though)

Working implementation of console app

---

src/main/java/console_app/ApplicationDriver.java
src/main/java/console_app/MainController.java
src/main/java/console_app/task_to_event_adapters/TaskToEventController.java
src/main/java/services/event_from_task_creation/CalendarAnalyzer.java
src/main/java/services/event_from_task_creation/EventScheduler.java

Replaced auto behavior with just presenting the suggested time and having the user manually accept or choose their own time.
closes #61

Removed Auto Task-To-Event Converting

---

src/main/java/services/event_from_task_creation/EventScheduler.java
src/test/java/CalendarAnalyzerTest.java
src/test/java/EventSchedulerTest.java

no longer suggest past times or times closer than an hour from current

Update Time Suggestion Strategy

---

src/main/java/services/event_creation/EventInfoFromReader.java
src/main/java/services/task_presentation/TaskOutputter.java
src/main/java/services/task_presentation/TodoListInfoFromTaskReaders.java
src/test/java/EventGetterTest.java
src/test/java/TaskInfoFromTaskReaderTest.java
src/test/java/TaskOutputterTest.java
src/test/java/TaskSaverTest.java

Test jenci

---

src/main/java/gui/GUIDriver.java
src/main/java/gui/model/EventModelManager.java
src/main/java/gui/utility/EventHelper.java
src/main/java/gui/utility/InstanceMapper.java
src/main/java/gui/utility/NavigationHelper.java
src/main/java/gui/view/BasicPageController.java
src/main/java/gui/view/DailyCalendarController.java
src/main/java/gui/view/MonthlyCalendarController.java
src/main/java/gui/view/NavigationCollapsedPanelController.java
src/main/java/gui/view/NavigationExtendedPanelController.java
src/main/java/gui/view/ViewModelBindingController.java
src/main/java/gui/view/WeeklyCalendarController.java
src/main/java/gui/view_model/MonthlyCalendarViewModel.java
src/main/java/gui/view_model/ViewModel.java
src/main/java/gui/view_model/ViewModelFactory.java
src/main/java/gui/view_model/WeeklyCalendarViewModel.java
src/main/resources/monthlyCalendar.fxml
src/main/resources/weeklyCalendar.fxml

1. Created view model factory to return view models, to be injected into fx-controllers (the model class that view models depend on are not included, but a sample/ dummy model is included for me to try out/ test)
2. Added a ViewModelBindingController interface for all controllers who need a view model to implement (actually only the Navigation controllers do not need to implement this)
3. Added `InstanceMapper` which maps a controller class to its corresponding view model class. `NavigationHelper` holds an instance of this mapper and uses it to determine which view models to inject into each controller upon instantiation.

GUI refactoring

---

src/main/java/services/event_creation/EventAdderWithNotification.java
src/main/java/services/notification/NotificationAdder.java
src/main/java/services/task_creation/TaskAdderWithNotification.java

After introducing notification system, a new notification will be created when a new task/event is added.
We will use proxy design pattern for this extra work.
See the left bottom part of this [UML](https://app.diagrams.net/#G1d6-EMS59UJDCOAwQ8ZjQiKCUdbTaeNX0)
The `completeTask` method will be removed after #115 is merged.
[Action Failure](https://github.com/gradle/wrapper-validation-action/issues/40)

added proxy for creating task and event

---

src/main/java/console_app/ApplicationDriver.java

Don't ask. I blame long nights.
Please accept the revert.

revert accidental change

---

src/main/java/data_gateway/notification/JsonNotificationAdapter.java

Small change, adding save method for Notification JSON adapter

Added save feature for notifications

---

TaskData.json
src/main/java/gui/GUIDriver.java
src/main/java/gui/view/TodoListPageController.java
src/main/java/gui/view_model/TodoListPageViewModel.java
src/main/java/gui/view_model/ViewModelFactory.java

Now the Todo List page is able to load the existing tasks when the program starts running.

Todo list page view model

---

src/main/java/entity/dates/DecoratorStrategy.java
src/main/java/services/strategybuilding/Rules.java
src/main/java/services/strategybuilding/StrategyBuilder.java
src/main/java/services/strategybuilding/strategies/EndRestrictionDecorator.java
src/main/java/services/strategybuilding/strategies/StartRestrictionDecorator.java
src/test/java/StrategyBuilderTest.java

This process helps the builder be more generic, apply OCP better, as well as making it easier to serialize strategies (well reconstruct the serialized strategies).

generalized base builder methods

---

src/main/java/gui/GUIDriver.java
src/main/java/gui/utility/NavigationHelper.java
src/main/java/gui/view/MonthlyCalendarController.java
src/main/java/gui/view/WeeklyCalendarController.java

Fixed the following bugs:
1. todolist not showing the existing list of tasks from JSON file
2. pomodoro page not showing
3. removed code related to day calendar since we removed it
4. changed nav helper's `enterHomePage` to be entering calendar page since home page is missing now
5. added initialization of controller in GUIDriver for the calendar page that we are loading first

Fixed bugs in GUI

---

src/main/java/datagateway/SettingAccessor.java
src/main/java/datagateway/SettingDataStructure.java
src/main/java/datagateway/UserSettingsGateway.java
src/main/java/services/updateentities/SettingsUpdater.java

There were two data gateway packages and two update entities packages. They were just named slightly differently (one with snake case and one without)

merged duplicate packages
